#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'glass'

require_relative 'values'

host = ARGV.shift

raise "hostname [#{host}] is not valid" unless host =~ /^[a-z0-9]+$/

values = ARGV

config = Glass::Config.new(:proxy => :mongo)

split(values).each do |key, value|
  config.proxy.manager.set_host_value(host, key, value)
end

