#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'glass'

require_relative 'values'

values = ARGV

config = Glass::Config.new(:proxy => :mongo)

split(values).each do |key, value|
  config.proxy.manager.set_global_value(key, value)
end

