#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'cia'

require_relative 'utils'

key = ARGV.shift

config = Cia::Config.new(:proxy => :mongo)

puts "global value"
puts "key is #{key}"

config.proxy.manager.set_global_value(key, values(ARGV))

