#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'cia'

host = ARGV.shift

config = Cia::Config.new(:proxy => :mongo)

Cia::Proxy::Base::LOG = Logger.new(STDOUT)

puts ""
puts ""

config.fetch(ARGV.first).inspect
