#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'cia'

require_relative 'utils'

role = ARGV.shift

raise "role [#{role}] is not valid" unless role =~ /^[a-z0-9]+$/

key = ARGV.shift

config = Cia::Config.new(:proxy => :mongo)

puts "role is #{role}"
puts "key is #{key}"

config.proxy.manager.set_role_value(role, key, values(ARGV))

