#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'cia'

host = ARGV.shift
roles = ARGV

config = Cia::Config.new(:proxy => :mongo)

config.proxy.manager.set_host_value(host, "roles", roles)

